log:
  level: ERROR
api:
  dashboard: true
  insecure: false
  debug: false
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yaml
certificatesResolvers:
  le:
    acme:
      email: larryare@disroot.org
      storage: acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # uncomment line above, to test your configuration, not using it may
      # result in exceeding allowed certificates
      dnsChallenge:
        provider: digitalocean
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"